name = "region-workers-example"
type = "webpack"
account_id = "dc56444c4c955a1653106ccf997c1067"
workers_dev = true

[env.production]
workers_dev = false
route = "https://region.signalnerve.com/"
zone_id = "b6e4c59655bb1e7d3d49419fa667ae53"
